blog/urls.py
from blog.apps import BlogConfig
from django.urls import path

from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogDeleteView, BlogUpdateView

app_name = BlogConfig.name
urlpatterns = [
    path('blog/', BlogListView.as_view(), name='blog_list'),
    path('blog_create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog_view/<int:pk>', BlogDetailView.as_view(), name='blog_view'),
    path('blog_delete/<int:pk>', BlogDeleteView.as_view(), name='blog_delete'),
    path('blog_update/<int:pk>', BlogUpdateView.as_view(), name='blog_update')

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('service.urls', namespace='service')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service/urls.py
from django.urls import path
from service.apps import ServiceConfig
from service.views import СustomerListView, СustomerCreateView, СustomerDetailView, \
    СustomerUpdateView, СustomerDeleteView, LetterListView, LetterCreateView, LetterDetailView, \
    LetterUpdateView, LetterDeleteView, HomeView

app_name = ServiceConfig.name

urlpatterns = [
    path('customer_list/', СustomerListView.as_view(), name='list'),
    path('create/', СustomerCreateView.as_view(), name='create'),
    path('view/<int:pk>/', СustomerDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', СustomerUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', СustomerDeleteView.as_view(), name='delete'),
    path('letter/', LetterListView.as_view(), name='list_letter'),
    path('letter/create/', LetterCreateView.as_view(), name='create_letter'),
    path('letter/view/<int:pk>', LetterDetailView.as_view(), name='view_letter'),
    path('letter/edit/<int:pk>/', LetterUpdateView.as_view(), name='edit_letter'),
    path('letter/delete/<int:pk>/', LetterDeleteView.as_view(), name='delete_letter'),
    path('', HomeView.as_view(), name='logs_list'),

]

service/models.py
from django.db import models

AUTH_USER_MODEL = 'users.User'
NULLABLE = {'blank': True, 'null': True}


class Сustomer(models.Model):
    email = models.EmailField(verbose_name='почта')
    name = models.CharField(max_length=300, verbose_name='ФИО')
    comment = models.TextField(verbose_name='комментарий')
    author = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Автор',
                               **NULLABLE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'


class Letter(models.Model):

    choice_periodicity = [('day', "раз в день"), ('week', "раз в неделю"), ('month', "раз в месяц")]
    choice_status = [('CREATED', "создана"), ('STARTED', "запущена"), ('COMPLETED', "завершена")]

    time = models.TimeField(verbose_name='Время рассылки', **NULLABLE, auto_now_add=True,)
    finish_date = models.DateField(verbose_name='Дата завершения рассылки', **NULLABLE)
    finish_time = models.TimeField(verbose_name='Время завершения рассылки', **NULLABLE)
    periodicity = models.CharField(max_length=100, verbose_name='переодичность рассылки',
                                   choices=choice_periodicity)
    status = models.CharField(max_length=100, verbose_name='статус рассылки', choices=choice_status)
    clients = models.ManyToManyField(Сustomer, verbose_name='клиенты рассылки')
    name = models.CharField(max_length=100, verbose_name='название рассылки', **NULLABLE)
    is_active = models.BooleanField(verbose_name='активность рассылки', default=True)
    author = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Автор',
                               **NULLABLE)
    create_date = models.DateField(auto_now_add=True, verbose_name='Дата создания', **NULLABLE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылки'

        permissions = [
            ('can_change_is_active_permission', 'Can change active latter'),
        ]

    def delete(self, *args, **kwargs):
        self.is_active = False
        self.status = 'COMPLETED'
        self.save()


class Message(models.Model):
    title = models.CharField(max_length=100, verbose_name='тема письма')
    text = models.TextField(verbose_name='тело письма', **NULLABLE)
    message = models.ForeignKey(Letter, on_delete=models.CASCADE,
                                verbose_name='настройка сообщения', **NULLABLE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'сообщения'


class Logs(models.Model):
    data_time = models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отправки')
    status = models.CharField(max_length=100, verbose_name='статус попытки')
    answer = models.BooleanField(verbose_name='ответ почтового сервера')

    mailing_list = models.ForeignKey(Letter, on_delete=models.CASCADE,
                                     verbose_name='рассылка', **NULLABLE)
    client = models.ForeignKey(Сustomer, on_delete=models.CASCADE, verbose_name='клиент рассылки',
                               **NULLABLE)

    def __str__(self):
        return self.status

    class Meta:
        verbose_name = 'логи'
        verbose_name_plural = 'логи'

service/forms.py
from django import forms
from service.models import Сustomer, Letter, Message


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=250)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(max_length=250)


class СustomerForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Сustomer
        fields = ('email', 'name', 'comment')


class LetterForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Letter
        fields = ('name',  'periodicity', 'clients', )


class MessageForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Message
        fields = '__all__'

service/views.py
from random import sample
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView, \
    TemplateView

from blog.models import Blog

from service.models import Сustomer, Letter, Message, Logs
from django.urls import reverse_lazy, reverse

from service.forms import СustomerForm, LetterForm, MessageForm
from django.forms import inlineformset_factory

from service.service import MessageService, get_count_mailing, get_active_mailing, \
    get_unique_clients, delete_task, send_mailing


class СustomerListView(LoginRequiredMixin, ListView):
    model = Сustomer

    def get_queryset(self):
        customer_list = super().get_queryset()
        if self.request.user.is_bloked == True:
            raise Http404("Вы заблокрованы")
        else:
            return customer_list


class СustomerCreateView(LoginRequiredMixin, CreateView):
    model = Сustomer
    form_class = СustomerForm
    success_url = reverse_lazy('service:list')




class СustomerDetailView(LoginRequiredMixin, DetailView):
    model = Сustomer


class СustomerUpdateView(LoginRequiredMixin, UpdateView):
    model = Сustomer
    fields = ('name', 'email', 'comment')
    success_url = reverse_lazy('service:list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user.groups.filter(
            name='Модератор').exists() or self.request.user.is_superuser:
            return self.object
        if self.object.author != self.request.user:
            raise Http404("Вы не можете редактировать чужого пользователя")
        return self.object


class СustomerDeleteView(LoginRequiredMixin, DeleteView):
    model = Сustomer
    success_url = reverse_lazy('service:list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user.is_superuser:
            return self.object
        if self.object.author != self.request.user:
            raise Http404("Вы не можете удалять другого пользователя")
        return self.object


class LetterListView(LoginRequiredMixin, ListView):
    model = Letter

    def get_queryset(self):
        letter_list = super().get_queryset()
        if self.request.user.is_bloked == True:
            raise Http404("Вы заблокрованы")
        else:
            return letter_list


class LetterCreateView(LoginRequiredMixin, CreateView):
    model = Letter
    form_class = LetterForm
    success_url = reverse_lazy('service:list_letter')

    def get_queryset(self):
        user = self.request.author
        mailing = Letter.objects.all()
        if user.is_staff or user.is_superuser:
            queryset = mailing
        else:
            queryset = mailing.clients.filter(user=user)
        return queryset

    def form_valid(self, form):
        mail = form.save(commit=False)
        mail.author = self.request.user
        mail.status = 'CREATED'
        mail.save()

        message_service = MessageService(mail)
        send_mailing(mail)
        message_service.create_task()
        mail.status = 'STARTED'
        mail.save()

        return super(LetterCreateView, self).form_valid(form)


class LetterDetailView(LoginRequiredMixin, DetailView):
    model = Letter


class LetterUpdateView(LoginRequiredMixin, UpdateView):
    model = Letter
    form_class = LetterForm
    success_url = reverse_lazy('service:list_letter')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        MessageFormset = inlineformset_factory(Letter, Message, extra=1, form=MessageForm)

        if self.request.method == 'POST':
            context_data['formset'] = MessageFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = MessageFormset(instance=self.object)

        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user.groups.filter(
            name='Модератор').exists() or self.request.user.is_superuser:
            return self.object
        if self.object.author != self.request.user:
            raise Http404("Вы не можете редактировать чужую подписку")
        return self.object


class LetterDeleteView(LoginRequiredMixin, DeleteView):
    model = Letter
    success_url = reverse_lazy('service:list_letter')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user.is_superuser:
            return self.object
        if self.object.author != self.request.user:
            raise Http404("Вы не можете удалить чужую подписку")
        return self.object

    def toggle_status(request, pk):
        """Функция, позволяющая отключать и активировать рассылку"""
        mailing = get_object_or_404(Letter, pk=pk)
        message_service = MessageService(mailing)
        if mailing.status == 'STARTED' or mailing.status == 'CREATED':
            delete_task(mailing)
            mailing.status = 'COMPLETED'
        else:
            message_service.create_task()
            mailing.status = 'STARTED'

        mailing.save()

        return redirect(reverse('service:list_letter'))





class HomeView(TemplateView):
    """Представление главной страницы сервиса"""
    extra_context = {
        'title': 'SkyBlog'
    }
    template_name = 'service/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        all_posts = list(Blog.objects.all())
        context['random_post'] = sample(all_posts, min(3, len(all_posts)))
        context['count_mailing'] = get_count_mailing()
        context['active_mailing'] = get_active_mailing()
        context['unique_clients'] = get_unique_clients()

        return context

service/templates/service/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>

{% include 'service/includes/inc_service_menu.html' %}


<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
                    {% block content %}
                    {% endblock %}


    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2024</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

service/templates/service/home.html
{% extends 'service/base.html'%}
{% load mediapath %}
{% block content %}
<div class="table">
    <table>
        <tr>
            <td>
                Количество рассылок всего
            </td>
            <td>
                {{count_mailing}}
            </td>
        </tr>
        <tr>
            <td>
                Количество активных рассылок:
            </td>
            <td>
                {{active_mailing}}
            </td>
        </tr>
        <tr>
            <td>
                Количество уникальных клиентов для рассылок:
            </td>
            <td>
                {{unique_clients}}
            </td>

        </tr>
    </table>
</div>


{% for object in random_post %}
<div class="table">
     <div class="col-6">
    <table>
              <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <img src="{{ object.image| my_teg }}" alt=" " />
                   <p class="card-text">{{ object.title |title }}</p>
                    <p class="card-text">{{ object.text   }}</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
    </div>
</div>
                    </div>

{% endfor %}
</div>
           </table>
{% endblock %}

service/templates/service/letter_confirm_delete.html
{% extends 'service/base.html'%}
{% block content %}

<div class="row">
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <p> Хотите удалить подписку {{ object.status }} для {{ object.clients }} ?></p>
                            <button type="submit" class="btn btn-outline-danger">
                                    Подтвердить
                            </button>
                            <a href="{% url 'service:list'%}"> Отмена </a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

service/templates/service/letter_detail.html
{% extends 'service/base.html'%}
{% block content %}
<div class="row">
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card header">
                        <h3 class="card-title">
                            Информация о подписке
                        </h3>
                    </div>
                    <div class="card body">
                        <table class="table">
                            <tr>
                                <td Информация о рассылке ></td>
                            </tr>
                              <tr>
                                  <tr>
                                <td>Название: {{ object.name }}</td>
                             </tr>
                             <tr>
                                <td>Автор рассылки: {{ object.author }}</td>
                             </tr>
                                <td> Отправление с: {{ object.time_on }}</td>
                              </tr>
                            <tr>
                                <td> Отправление до: {{ object.time_off }}</td>
                              </tr>
                             <tr>
                                <td>Переодинчость: {{ object.periodicity }}</td>
                             </tr>
                            <tr>
                                <td>Статус: {{ object.status }}</td>
                             </tr>
                            <tr>
                                <td>Клиенты рассылки: {{ object.clients }}</td>
                             </tr>


                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>












{% endblock %}

service/templates/service/letter_form.html
{% extends 'service/base.html'%}
{% block content %}
                <div class="col-12">
                     <form class="row" method="post" enctype="multipart/form-data">
                                <div class="col-6">
                                    <div class="card">
                                        <div class="card header">
                                            <h3 class="card-title">
                                                Информация о подписке
                                            </h3>
                                            </div>
                                            <div class="card-body">
                                            {% csrf_token %}
                                            {{ form.as_p }}
                                                <button type="submit">
                                                        {% if object %}
                                                            Сохранить
                                                        {% else %}
                                                            Создать
                                                        {% endif %}
                                                </button>
                                        </div>
                                        <div class="card-footer"></div>
                                     </div>
                                 </div>

                            <div class="col-6">
<div class="card">
                                        <div class="card header">
                                            <h3 class="card-title">
                                                Настройка сообщения
                                            </h3>
                                            </div>
                                            <div class="card-body">
                                           {{ formset.management_form }}
                                                {% for form in formset.forms %}
                                                {{ form.as_p }}
                                                {% if not forloop.last %}
                                                <hr>
                                                 {% endif%}
                                                {% endfor %}

                                        </div>
                                        <div class="card-footer"></div>
                                     </div>
                            </div>
                     </form>
                </div>

{% endblock %}

service/templates/service/letter_list.html
{% extends 'service/base.html'%}
{% load static %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <div class="col-md-2 ">
     <a class="btn btn-primary" href="{% url 'service:create_letter' %}" >Добавить </a>
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  </div>
          </div>
   <h1 class="display-4" >Подписки</h1>
</div>
 <div class="album py-5 bg-light">
        <div class="container">

          <div class="row">
            {% for object in object_list %}
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <div class="card-body">
                   <p class="card-text">{{ object.name |title }}</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                         <a href="{% url 'service:view_letter' object.pk %}">
                      <button type="button" class="btn btn-sm btn-outline-primary">View</button></a>
                        <a href="{% url 'service:edit_letter' object.pk %}">
                      <button type="button" class="btn btn-sm btn-outline-primary">Edit</button></a>
                        <a href="{% url 'service:delete_letter' object.pk %}">
                        <button type="button" class="btn  btn-sm btn-outline-danger">Delete</button></a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>



    {% endblock %}

service/templates/service/сustomer_confirm_delete.html
{% extends 'service/base.html'%}
{% block content %}

<div class="row">
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <p> Хотите удалить пользователя {{ object.name }} ?></p>
                            <button type="submit" class="btn btn-outline-danger">
                                    Подтвердить
                            </button>
                            <a href="{% url 'service:list'%}"> Отмена </a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

service/templates/service/сustomer_detail.html
{% extends 'service/base.html'%}
{% block content %}
<div class="row">
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card header">
                        <h3 class="card-title">
                            Информация о пользователе
                        </h3>
                    </div>
                    <div class="card body">
                        <table class="table">
                            <tr>
                                <td Пользователь ></td>
                            </tr>
                              <tr>
                                <td>{{ object.name|title }}</td>
                              </tr>
                            <tr>
                                <td>{{ object.email }}</td>
                              </tr>
                             <tr>
                                <td>{{ object.comment }}</td>
                             </tr>

                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>












{% endblock %}

service/templates/service/сustomer_form.html
{% extends 'service/base.html'%}
{% block content %}

<div class="row">
    <div class="col-6">
        <div class="card">
            <div class="card body">
                <form method="post">
                    {% csrf_token %}
                            {{ form.as_p }}
                    <button type="submit">
                                {% if object %}
                                    Сохранить
                                {% else %}
                                    Создать
                                {% endif %}
                    </button>

                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

service/templates/service/сustomer_list.html
{% extends 'service/base.html'%}
{% load static %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <div class="col-md-2 ">
     <a class="btn btn-primary" href="{% url 'service:create' %}" >Добавить </a>
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  </div>
          </div>
   <h1 class="display-4" >Клиенты</h1>
</div>
 <div class="album py-5 bg-light">
        <div class="container">

          <div class="row">
            {% for object in object_list %}
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <div class="card-body">
                   <p class="card-text">{{ object.name |title }}</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                         <a href="{% url 'service:view' object.pk %}">
                      <button type="button" class="btn btn-sm btn-outline-primary">View</button></a>
                        <a href="{% url 'service:edit' object.pk %}">
                      <button type="button" class="btn btn-sm btn-outline-primary">Edit</button></a>
                        <a href="{% url 'service:delete' object.pk %}">
                        <button type="button" class="btn  btn-sm btn-outline-danger">Delete</button></a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>



    {% endblock %}