blog/urls.py
from blog.apps import BlogConfig
from django.urls import path

from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogDeleteView, BlogUpdateView

app_name = BlogConfig.name
urlpatterns = [
    path('blog/', BlogListView.as_view(), name='blog_list'),
    path('blog_create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog_view/<int:pk>', BlogDetailView.as_view(), name='blog_view'),
    path('blog_delete/<int:pk>', BlogDeleteView.as_view(), name='blog_delete'),
    path('blog_update/<int:pk>', BlogUpdateView.as_view(), name='blog_update')

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('service.urls', namespace='service')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse

NULLABLE = {'blank': True, 'null': True}
AUTH_USER_MODEL = 'users.User'

class Blog(models.Model):
    activity = [(True, 'Опубликовано'),
                (False, 'Неопубликовано')]

    title = models.CharField(max_length=100, verbose_name='название')
    slug = models.SlugField(max_length=255, unique=True, **NULLABLE, verbose_name='URL')
    author = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Автор', **NULLABLE)
    text = models.TextField(verbose_name='текст', **NULLABLE)
    image = models.ImageField(upload_to='blogs/', verbose_name='изображение', **NULLABLE)
    date_create = models.DateTimeField(verbose_name='дата создания', **NULLABLE)
    is_published = models.BooleanField(verbose_name='признак публикации', default=True, choices=activity)
    count_views = models.IntegerField(default=0, verbose_name='количество просмотров')

    def __str__(self):
        return self.title


    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'


    def get_absolute_url(self):
        return reverse('blog:blog_detail', kwargs={'slug': self.slug})

blog/forms.py
from django import forms

from blog.models import Blog
from service.forms import StyleFormMixin

class BlogForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'text',  'image', 'is_published')

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from pytils.translit import slugify
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView
from django.utils import timezone
from blog.forms import BlogForm
from blog.models import Blog


class BlogListView(LoginRequiredMixin, ListView):
    model = Blog

    def get_queryset(self):
        product_list = super().get_queryset()
        if self.request.user.groups.filter(
            name='Модератор').exists() or self.request.user.is_superuser and self.request.user.is_bloked == False:
            return product_list
        elif self.request.user.is_bloked == True:
            raise Http404("Вы заблокрованы")
        else:
            return product_list.filter(is_published=True)


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:blog_list')

    def form_valid(self, form):
        self.object = form.save()
        self.object.author = self.request.user
        self.object.date_create = timezone.localtime(timezone.now())
        self.object.save()
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)


class BlogDetailView(LoginRequiredMixin, DetailView):
    model = Blog

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()
        return super().form_valid(form)

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.count_views += 1
        self.object.save()
        return self.object


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user.is_superuser:
            return self.object
        if self.object.author != self.request.user:
            raise Http404("Вы не можете удалять чужую статью")
        return self.object


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:blog_list')

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()
        return super().form_valid(form)

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user.groups.filter(
            name='Модератор').exists() or self.request.user.is_superuser:
            return self.object
        if self.object.author != self.request.user:
            raise Http404("Вы не являетесь автором данной статьи")
        return self.object

blog/templates/blog/blog_confirm_delete.html
{% extends 'service/base.html'%}
{% block content %}

<div class="row">
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <p> Хотите удалить статью {{ object.title }} ?></p>
                            <button type="submit" class="btn btn-outline-danger">
                                    Подтвердить
                            </button>
                            <a href="{% url 'blog:blog_list'%}"> Отмена </a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'service/base.html'%}
{% block content %}
<div class="row">
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card header">
                        <h3 class="card-title">
                            Информация о блоге
                        </h3>
                    </div>
                    <div class="card body">
                        <table class="table">
                            <tr>
                                <td Статья ></td>
                            </tr>
                              <tr>
                                <td>Название: {{ object.title }} </td>
                              </tr>
                            <tr>
                                <td>Url : {{ object.slug }}</td>
                              </tr>
                             <tr>
                                <td>Автор: {{ object.author }}</td>
                             </tr>
                            <tr>
                                <td>Содержимое: {{ object.text }}</td>
                             </tr>
                             <tr>
                                <td>Дата создания: {{ object.date_create }}</td>
                             </tr>
                             <tr>
                                <td>Количество просмотров: {{ object.count_views }}</td>
                             </tr>



                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>












{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'service/base.html'%}
{% block content %}
                <div class="col-12">
                     <form class="row" method="post" enctype="multipart/form-data">
                                <div class="col-6">
                                    <div class="card">
                                        <div class="card header">
                                            <h3 class="card-title">
                                                Информация о блоге
                                            </h3>
                                            </div>
                                            <div class="card-body">
                                            {% csrf_token %}
                                            {{ form.as_p }}
                                                <button type="submit">
                                                        {% if object %}
                                                            Сохранить
                                                        {% else %}
                                                            Создать
                                                        {% endif %}
                                                </button>
                                        </div>
                                        <div class="card-footer"></div>
                                     </div>
                                 </div>


                            </div>
                     </form>
                </div>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'service/base.html'%}
{% load static %}
{% load mediapath %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <div class="col-md-2 ">
     <a class="btn btn-primary" href="{% url 'blog:blog_create' %}" >Добавить </a>

          </div>
   <h1 class="display-4" >Блог</h1>
</div>
 <div class="album py-5 bg-light">
        <div class="container">

          <div class="row">
            {% for object in object_list %}
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <img src="{{ object.image| my_teg }}" alt=" " />
                   <p class="card-text">{{ object.title |title }}</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                         <a href="{% url 'blog:blog_view' object.pk %}">
                      <button type="button" class="btn btn-sm btn-outline-primary">View</button></a>
                        <a href="{% url 'blog:blog_update' object.pk %}">
                      <button type="button" class="btn btn-sm btn-outline-primary">Edit</button></a>
                        <a href="{% url 'blog:blog_delete' object.pk %}">
                        <button type="button" class="btn  btn-sm btn-outline-danger">Delete</button></a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>



    {% endblock %}