blog/urls.py
from blog.apps import BlogConfig
from django.urls import path

from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogDeleteView, BlogUpdateView

app_name = BlogConfig.name
urlpatterns = [
    path('blog/', BlogListView.as_view(), name='blog_list'),
    path('blog_create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog_view/<int:pk>', BlogDetailView.as_view(), name='blog_view'),
    path('blog_delete/<int:pk>', BlogDeleteView.as_view(), name='blog_delete'),
    path('blog_update/<int:pk>', BlogUpdateView.as_view(), name='blog_update')

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('service.urls', namespace='service')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from users.apps import UsersConfig
from django.contrib.auth.views import LogoutView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from users.views import RegisterView, LoginView, UserUpdateView, get_new_password, VerifyEmailView, \
    UserListView, UserDetailView, UserDeleteView
from django.urls import path, reverse_lazy

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('profile/genpassword', get_new_password, name='get_new_password'),
    path('verify_email//<str:token>/', VerifyEmailView.as_view(), name='verify_email'),
    path('user_list/', UserListView.as_view(), name='user_list'),
    path('user_view/<int:pk>/', UserDetailView.as_view(), name='user_view'),
    path('user_delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),

    path('password-reset/',
         PasswordResetView.as_view
         (template_name="users/password_reset_form.html",
          email_template_name="users/password_reset_email.html",
          success_url=reverse_lazy("users:password_reset_done")),
         name='password_reset'),

    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view
         (template_name='users/password_reset_confirm.html',
          success_url=reverse_lazy('users:password_reset_complete')
          ),
         name='password_reset_confirm'),

    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
         name='password_reset_done'),

    path('password-reset/complete',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete')

]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

NULLABLE = {'blank': True, 'null': True}
AUTH_USER_MODEL = 'users.User'

class User(AbstractUser, models.Model):
    DoesNotExist = None
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')
    FIO = models.CharField(max_length=300, verbose_name='ФИО',  **NULLABLE)
    comment = models.TextField(verbose_name='комментарий',  **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    phone = models.CharField(max_length=50, verbose_name='телефон')
    county = models.CharField(max_length=50, verbose_name='страна')
    email_verification_token = models.CharField(max_length=255, **NULLABLE)
    is_bloked = models.BooleanField(verbose_name='блокировка пользователя', default=False)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        permissions = [
            ('can_change_is_bloked_permission', 'Can bloked user'),
        ]

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from users.models import User
from django import forms


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError("пароли не совпадают")
        return cd['password1']



class UserForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'last_name', 'avatar', 'phone', 'county')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import random
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.http import Http404
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.views import View
from django.views.generic import CreateView, UpdateView, ListView, DetailView, DeleteView
from users.models import User
from users.forms import UserRegisterForm, UserForm
from django.urls import reverse_lazy, reverse
from django.contrib.auth.views import LoginView as BaseLoginView
from django.core.mail import send_mail, EmailMultiAlternatives
from django.conf import settings


class UserListView(LoginRequiredMixin, ListView):
    model = User

    def get_queryset(self):
        customer_list = super().get_queryset()
        if self.request.user.is_bloked == True:
            raise Http404("Вы заблокрованы")
        else:
            return customer_list

class UserDetailView(LoginRequiredMixin, DetailView):
    model = User


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user




class UserDeleteView(LoginRequiredMixin, DeleteView):
    model = User
    success_url = reverse_lazy('service:list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user.is_superuser:
            return self.object
        if self.object.pk != self.request.user.pk:
            raise Http404("Вы не можете удалять другого пользователя")
        return self.object


class LoginView(BaseLoginView):
    template_name = 'users/login.html'
    extra_context = {'title': "Авторизация"}


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        response = super().form_valid(form)
        new_user = form.save(commit=False)
        new_user.is_active = False
        # Функционал для отправки письма и генерации токена
        token = default_token_generator.make_token(new_user)
        new_user.email_verification_token = token
        new_user.email_verification_token = token
        new_user.save()
        current_site = get_current_site(self.request)

        mail_subject = ('Подтверждение регистрации')
        html_message = render_to_string(
            'users/verify_email.html',
            {
                'user': new_user,
                'domain': current_site.domain,
                'token': token
            })

        plain_message = strip_tags(html_message)
        message = EmailMultiAlternatives(mail_subject,
                                         plain_message,
                                         settings.EMAIL_HOST_USER,
                                         [new_user.email]
                                         )

        message.attach_alternative(html_message, "text/html")
        message.send()
        return response


class VerifyEmailView(View):

    def get(self, request, token):
        try:
            user = User.objects.get(email_verification_token=token)
            user.is_active = True
            user.save()
            return render(request, 'users/registration_success.html')
        except User.DoesNotExist:
            return render(request, 'users/registration_failed.html')






def get_new_password(request):
    new_password = ''.join([str(random.randint(0, 9)) for _ in range(12)])
    send_mail(
        subject='Смена пароля',
        message=f'Ваш новый пароль {new_password}',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email]
    )
    request.user.set_password(new_password)
    request.user.save()
    return redirect(reverse('catalog:catalog_product'))

users/templates/users/login.html
{% extends 'service/base.html'%}
{% block content %}

<div class="col-12">
                     <form class="row" method="post" enctype="multipart/form-data">
                                <div class="col-6">
                                    <div class="card">
                                        <div class="card header">
                                            <h3 class="card-title">
                                                Вход
                                            </h3>
                                            </div>
                                            <div class="card-body">
                                            {% csrf_token %}
                                            {{ form.as_p }}
                                                <button type="submit">Войти!</button>
                                                <p><a href="{% url 'users:password_reset' %}">Забыли пароль?</a></p>
                                        </div>
                                        <div class="card-footer"></div>
                                     </div>

                                 </div>


{% endblock %}

users/templates/users/logout.html
{% extends 'service/base.html'%}
{% block content %}

<div class="col-12">
                     <form class="row" method="post" enctype="multipart/form-data">
                                <div class="col-6">
                                    <div class="card">
                                        <div class="card header">
                                            <h3 class="card-title">
                                                Вы уверены, что хотите выйти ?
                                            </h3>
                                            </div>
                                            <div class="card-body">
                                            {% csrf_token %}
                                            {{ form.as_p }}
                                                <button type="submit">

                                                            Да, выйти

                                                </button>
                                        </div>
                                        <div class="card-footer"></div>
                                     </div>
                                 </div>


{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'service/base.html'%}
{% block content %}
<h1>Новый пароль</h1>
<form method="post">
     {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}: </label>{{f}} </p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit">Сохранить </button> </p>
</form>

{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'service/base.html'%}
{% load i18n %}


{% block content %}
<hi>Сброс пароля</hi>


<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>

{% endblock %}

users/templates/users/password_reset_email.html
{% extends 'service/base.html'%}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

    Ваш новый пароль
{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends 'service/base.html'%}
{% block content %}
<h1>Восстановление пароля</h1>
<form method="post">
     {% csrf_token %}
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}: </label>{{f}} </p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit">Сбросить по email </button> </p>
</form>
{% endblock %}

users/templates/users/register.html
{% extends 'service/base.html'%}
{% block content %}

<div class="col-12">
                     <form class="row" method="post" enctype="multipart/form-data">
                                <div class="col-6">
                                    <div class="card">
                                        <div class="card header">
                                            <h3 class="card-title">
                                                Регистрация
                                            </h3>
                                            </div>
                                            <div class="card-body">
                                            {% csrf_token %}
                                            {{ form.as_p }}
                                                <button type="submit">
                                                            Регистрация
                                                </button>
                                        </div>
                                        <div class="card-footer"></div>
                                     </div>
                                 </div>


{% endblock %}

users/templates/users/register_done.html
{% extends 'service/base.html'%}
{% block content %}
<h1>Добро пожаловать</h1>

<p>Вы успешно зарегестрировались на сайте! Для входа в систему необходимо авторизоваться на сайте
<a href="{% url 'users:login '%}">по ссылке</a></p>
{% endblock %}

users/templates/users/registration_failed.html
{% extends 'service/base.html'%}
<p>Неверная ссылка подтверждения.</p>

users/templates/users/registration_success.html
<h1>Поздравляем!</h1>
<p>Вы успешно зарегистрировались на нашем портале.</p>
<a href="{% url 'users:login' %}">Войти</a>

users/templates/users/user_detail.html
{% extends 'service/base.html'%}
{% block content %}
<div class="row">
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card header">
                        <h3 class="card-title">
                            Информация о пользователе
                        </h3>
                    </div>
                    <div class="card body">
                        <table class="table">
                            <tr>
                                <td Пользователь ></td>
                            </tr>
                              <tr>
                                <td>{{ object.FIO|title }}</td>
                              </tr>
                            <tr>
                                <td>{{ object.phone }}</td>
                              </tr>
                             <tr>
                                <td>{{ object.county }}</td>
                             </tr>
                            <tr>
                                <td>{{ object.comment }}</td>
                             </tr>


                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>












{% endblock %}

users/templates/users/user_form.html
{% extends 'service/base.html'%}
{% block content %}

<div class="col-12">
                     <form class="row" method="post" enctype="multipart/form-data">
                                <div class="col-6">
                                    <div class="card">
                                        <div class="card header">
                                            Мой профиль
                                            </div>
                                            </div>
                                            <div class="card-body">
                                                <form method="post" enctype="multipart/form-data">
                                            {% csrf_token %}
                                            {{ form.as_p }}
                                                <button type="submit" class="btn btn-success">Сохранить</button>
                                                </form>
                                        </div>
                                    <div class="card-footer"></div>
                                    <a href="{% url 'users:get_new_password' %}" class="btn btn-danger">Cгенерировать пароль</a>
                                    </div>






{% endblock %}

users/templates/users/user_list.html
{% extends 'service/base.html'%}
{% load static %}
{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">

          </div>
   <h1 class="display-4" >Пользователи</h1>
</div>
 <div class="album py-5 bg-light">
        <div class="container">

          <div class="row">
            {% for object in object_list %}
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <div class="card-body">
                   <p class="card-text">{{ object.email |title }}</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                         <a href="{% url 'users:user_view' object.pk %}">
                      <button type="button" class="btn btn-sm btn-outline-primary">View</button></a>
                        <a href="{% url 'users:user_delete' object.pk %}">
                        <button type="button" class="btn  btn-sm btn-outline-danger">Delete</button></a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>



    {% endblock %}

users/templates/users/verify_email.html
<div class="text-center">
    {% csrf_token %}
    <h3 class="card-title">Подтвердите вашу электронную почту</h3>
    <p>Поздравляем, Вы зарегистрировались на нашем портале!</p>
    <p>Для завершения регистрации и подтверждения вашей электронной почты, пожалуйста пройдите по ссылке:</p>
    <p><a href="http://{{ domain }}{% url 'users:verify_email' token=token %}">Подтвердить электронную почту</a> </p>
</div>